var $intern_181 = '102', $intern_180 = '110px', $intern_179 = '460px';
function com_google_gwt_user_client_ui_HorizontalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(this$static, align){
  this$static.com_google_gwt_user_client_ui_HorizontalPanel_horzAlign = align;
}

function com_google_gwt_user_client_ui_VerticalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(this$static, align){
  this$static.com_google_gwt_user_client_ui_VerticalPanel_horzAlign = align;
}

function pur_gwtplatform_samples_events_InsertCompleteEvent_InsertCompleteEvent__Lpur_gwtplatform_samples_model_Data_2V(){
  pur_gwtplatform_samples_events_InsertCompleteEvent_$clinit__V();
}

function pur_gwtplatform_samples_events_InsertCompleteEvent(){
}

_ = pur_gwtplatform_samples_events_InsertCompleteEvent_InsertCompleteEvent__Lpur_gwtplatform_samples_model_Data_2V.prototype = pur_gwtplatform_samples_events_InsertCompleteEvent.prototype = new com_google_gwt_event_shared_GwtEvent;
_.dispatch__Lcom_google_gwt_event_shared_EventHandler_2V = function pur_gwtplatform_samples_events_InsertCompleteEvent_dispatch__Lcom_google_gwt_event_shared_EventHandler_2V(handler){
  pur_gwtplatform_samples_presenter_MainPresenter_$refreshDataGrid__Lpur_gwtplatform_samples_presenter_MainPresenter_2V(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(handler, Q$pur_gwtplatform_samples_events_InsertCompleteEvent$InsertCompleteHandler), Q$pur_gwtplatform_samples_presenter_MainPresenter$4).pur_gwtplatform_samples_presenter_MainPresenter$4_this$0);
}
;
_.getAssociatedType__Lcom_google_gwt_event_shared_GwtEvent$Type_2 = function pur_gwtplatform_samples_events_InsertCompleteEvent_getAssociatedType__Lcom_google_gwt_event_shared_GwtEvent$Type_2(){
  return pur_gwtplatform_samples_events_InsertCompleteEvent_TYPE;
}
;
_.getClass__Ljava_lang_Class_2$ = function pur_gwtplatform_samples_events_InsertCompleteEvent_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1events_1InsertCompleteEvent_12_1classLit;
}
;
function pur_gwtplatform_samples_modules_IGinjectorImpl_$com$gwtplatform$mvp$client$HandlerContainerImpl_1automaticBind_1methodInjection_1_1__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_gwtplatform_mvp_client_AutobindDisable_2V(injectee, _0){
  injectee.automaticBind__Lcom_gwtplatform_mvp_client_AutobindDisable_2V(_0);
}

function pur_gwtplatform_samples_modules_IGinjectorImpl_$get_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2(this$static){
  var pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0;
  !this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$ = (pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0 = pur_gwtplatform_samples_modules_IGinjectorImpl_$pur$gwtplatform$samples$presenter$MessageInsertPresenter_1MessageInsertPresenter_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2((!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$google$web$bindery$event$shared$EventBus$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$google$web$bindery$event$shared$EventBus$_1annotation$$none$$ = new com_google_web_bindery_event_shared_SimpleEventBus_SimpleEventBus__V) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$google$web$bindery$event$shared$EventBus$_1annotation$$none$$), (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$views$MessageInsertView$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$views$MessageInsertView$_1annotation$$none$$ = new pur_gwtplatform_samples_views_MessageInsertView_MessageInsertView__Lpur_gwtplatform_samples_views_MessageInsertView$Binder_2V(new pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_MessageInsertView_1BinderImpl__V)) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$views$MessageInsertView$_1annotation$$none$$), (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$MyProxy$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$MyProxy$_1annotation$$none$$ = new pur_gwtplatform_samples_presenter_MessageInsertPresenterMyProxyImpl_MessageInsertPresenterMyProxyImpl__V) , !this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$proxy$PlaceManager$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$proxy$PlaceManager$_1annotation$$none$$ = pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$modules$PlaceManager$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_modules_PlaceManager_2(this$static)) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$proxy$PlaceManager$_1annotation$$none$$), !this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$shared$DispatchAsync$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$shared$DispatchAsync$_1annotation$$none$$ = pur_gwtplatform_samples_modules_IGinjectorImpl_$com$gwtplatform$dispatch$client$gin$DispatchAsyncModule_1provideDispatchAsync_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_gwtplatform_dispatch_client_gin_DispatchAsyncModule_2Lcom_gwtplatform_dispatch_client_ExceptionHandler_2Lcom_gwtplatform_dispatch_shared_SecurityCookieAccessor_2Lcom_gwtplatform_dispatch_client_actionhandler_ClientActionHandlerRegistry_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2(new com_gwtplatform_dispatch_client_gin_DispatchAsyncModule_DispatchAsyncModule__V, new com_gwtplatform_dispatch_client_DefaultExceptionHandler_DefaultExceptionHandler__V, new com_gwtplatform_dispatch_client_DefaultSecurityCookieAccessor_DefaultSecurityCookieAccessor__V, (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$client$actionhandler$ClientActionHandlerRegistry$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$client$actionhandler$ClientActionHandlerRegistry$_1annotation$$none$$ = new com_gwtplatform_dispatch_client_actionhandler_DefaultClientActionHandlerRegistry_DefaultClientActionHandlerRegistry__V) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$client$actionhandler$ClientActionHandlerRegistry$_1annotation$$none$$)))) , pur_gwtplatform_samples_modules_IGinjectorImpl_$com$gwtplatform$mvp$client$HandlerContainerImpl_1automaticBind_1methodInjection_1_1__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_gwtplatform_mvp_client_AutobindDisable_2V(pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0, (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$AutobindDisable$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$AutobindDisable$_1annotation$$none$$ = new com_gwtplatform_mvp_client_AutobindDisable_AutobindDisable__V) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$AutobindDisable$_1annotation$$none$$)) , pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0));
  return this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$;
}

function pur_gwtplatform_samples_modules_IGinjectorImpl_$pur$gwtplatform$samples$presenter$MessageInsertPresenter_1MessageInsertPresenter_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2(_0, _1, _3){
  return new pur_gwtplatform_samples_presenter_MessageInsertPresenter_MessageInsertPresenter__Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2V(_0, _1, _3);
}

_ = pur_gwtplatform_samples_modules_IGinjectorImpl$2$1.prototype;
_.onSuccess__V = function pur_gwtplatform_samples_modules_IGinjectorImpl$2$1_onSuccess__V(){
  com_gwtplatform_mvp_client_proxy_NotifyingAsyncCallback_$onSuccess__Lcom_gwtplatform_mvp_client_proxy_NotifyingAsyncCallback_2Ljava_lang_Object_2V(this.pur_gwtplatform_samples_modules_IGinjectorImpl$2$1_val$callback, pur_gwtplatform_samples_modules_IGinjectorImpl_$get_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2(this.pur_gwtplatform_samples_modules_IGinjectorImpl$2$1_this$1.pur_gwtplatform_samples_modules_IGinjectorImpl$2_this$0));
}
;
function pur_gwtplatform_samples_presenter_MessageInsertPresenter_MessageInsertPresenter__Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2V(eventBus, view, placeManager){
  com_gwtplatform_mvp_client_PresenterWidget_PresenterWidget__Lcom_google_web_bindery_event_shared_EventBus_2Lcom_gwtplatform_mvp_client_View_2V.call(this, eventBus, view);
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter_eventBus = eventBus;
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager = placeManager;
}

function pur_gwtplatform_samples_presenter_MessageInsertPresenter(){
}

_ = pur_gwtplatform_samples_presenter_MessageInsertPresenter_MessageInsertPresenter__Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2V.prototype = pur_gwtplatform_samples_presenter_MessageInsertPresenter.prototype = new com_gwtplatform_mvp_client_Presenter;
_.getClass__Ljava_lang_Class_2$ = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1presenter_1MessageInsertPresenter_12_1classLit;
}
;
_.onBind__V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_onBind__V(){
  com_gwtplatform_mvp_client_HandlerContainerImpl_$registerHandler__Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_google_web_bindery_event_shared_HandlerRegistration_2V(this, com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_insertButton, new pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_MessageInsertPresenter$1__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this), (com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_TYPE)));
  com_gwtplatform_mvp_client_HandlerContainerImpl_$registerHandler__Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_google_web_bindery_event_shared_HandlerRegistration_2V(this, com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_cancelButton, new pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_MessageInsertPresenter$2__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this), com_google_gwt_event_dom_client_ClickEvent_TYPE));
}
;
_.onReveal__V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_onReveal__V(){
}
;
_.revealInParent__V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_revealInParent__V(){
  com_gwtplatform_mvp_client_proxy_RevealRootContentEvent_$clinit__V();
  com_gwtplatform_mvp_client_PresenterWidget_$fireEvent__Lcom_gwtplatform_mvp_client_PresenterWidget_2Lcom_google_gwt_event_shared_GwtEvent_2V(this, new com_gwtplatform_mvp_client_proxy_RevealRootContentEvent_RevealRootContentEvent__Lcom_gwtplatform_mvp_client_Presenter_2V(this));
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_shared_HasHandlers, Q$com_gwtplatform_mvp_client_PresenterWidget]);
_.pur_gwtplatform_samples_presenter_MessageInsertPresenter_eventBus = null;
_.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager = null;
function pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_MessageInsertPresenter$1__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this$0){
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0 = this$0;
}

function pur_gwtplatform_samples_presenter_MessageInsertPresenter$1(){
}

_ = pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_MessageInsertPresenter$1__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V.prototype = pur_gwtplatform_samples_presenter_MessageInsertPresenter$1.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1presenter_1MessageInsertPresenter$1_12_1classLit;
}
;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  var data, key, stockstore;
  key = com_google_gwt_dom_client_Element_$getPropertyString__Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2Ljava_lang_String_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_keyStock.com_google_gwt_user_client_ui_UIObject_element, $intern_64);
  data = com_google_gwt_dom_client_Element_$getPropertyString__Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2Ljava_lang_String_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_dataStock.com_google_gwt_user_client_ui_UIObject_element, $intern_64);
  stockstore = com_google_gwt_storage_client_Storage_getLocalStorageIfSupported__Lcom_google_gwt_storage_client_Storage_2();
  !!stockstore && com_google_gwt_storage_client_StorageImplNonNativeEvents_$setItem__Lcom_google_gwt_storage_client_StorageImplNonNativeEvents_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2V(stockstore.com_google_gwt_storage_client_Storage_storage, key, data);
  com_google_web_bindery_event_shared_SimpleEventBus_$doFire__Lcom_google_web_bindery_event_shared_SimpleEventBus_2Lcom_google_web_bindery_event_shared_Event_2Ljava_lang_Object_2V(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.pur_gwtplatform_samples_presenter_MessageInsertPresenter_eventBus, new pur_gwtplatform_samples_events_InsertCompleteEvent_InsertCompleteEvent__Lpur_gwtplatform_samples_model_Data_2V(new pur_gwtplatform_samples_model_Data_Data__Ljava_lang_String_2Ljava_lang_String_2V(key, data)), null);
  com_gwtplatform_mvp_client_proxy_PlaceManagerImpl_$revealPlace__Lcom_gwtplatform_mvp_client_proxy_PlaceManagerImpl_2Lcom_gwtplatform_mvp_client_proxy_PlaceRequest_2ZV(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager, new com_gwtplatform_mvp_client_proxy_PlaceRequest_PlaceRequest__Ljava_lang_String_2V($intern_36), true);
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_dom_client_ClickHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0 = null;
function pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_MessageInsertPresenter$2__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this$0){
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0 = this$0;
}

function pur_gwtplatform_samples_presenter_MessageInsertPresenter$2(){
}

_ = pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_MessageInsertPresenter$2__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V.prototype = pur_gwtplatform_samples_presenter_MessageInsertPresenter$2.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1presenter_1MessageInsertPresenter$2_12_1classLit;
}
;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_keyStock.com_google_gwt_user_client_ui_UIObject_element[$intern_64] = $intern_7;
  com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_dataStock.com_google_gwt_user_client_ui_UIObject_element[$intern_64] = $intern_7;
  com_gwtplatform_mvp_client_proxy_PlaceManagerImpl_$revealPlace__Lcom_gwtplatform_mvp_client_proxy_PlaceManagerImpl_2Lcom_gwtplatform_mvp_client_proxy_PlaceRequest_2ZV(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager, new com_gwtplatform_mvp_client_proxy_PlaceRequest_PlaceRequest__Ljava_lang_String_2V($intern_36), true);
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_dom_client_ClickHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0 = null;
function pur_gwtplatform_samples_views_MessageInsertView_MessageInsertView__Lpur_gwtplatform_samples_views_MessageInsertView$Binder_2V(){
  this.pur_gwtplatform_samples_views_MessageInsertView_widget = pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_$createAndBindUi__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_2Lpur_gwtplatform_samples_views_MessageInsertView_2Lcom_google_gwt_user_client_ui_Widget_2(this);
}

function pur_gwtplatform_samples_views_MessageInsertView(){
}

_ = pur_gwtplatform_samples_views_MessageInsertView_MessageInsertView__Lpur_gwtplatform_samples_views_MessageInsertView$Binder_2V.prototype = pur_gwtplatform_samples_views_MessageInsertView.prototype = new com_gwtplatform_mvp_client_ViewImpl;
_.asWidget__Lcom_google_gwt_user_client_ui_Widget_2 = function pur_gwtplatform_samples_views_MessageInsertView_asWidget__Lcom_google_gwt_user_client_ui_Widget_2(){
  return this.pur_gwtplatform_samples_views_MessageInsertView_widget;
}
;
_.getClass__Ljava_lang_Class_2$ = function pur_gwtplatform_samples_views_MessageInsertView_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1views_1MessageInsertView_12_1classLit;
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$pur_gwtplatform_samples_views_IMessageInsertView, Q$pur_gwtplatform_samples_views_MessageInsertView]);
_.pur_gwtplatform_samples_views_MessageInsertView_cancelButton = null;
_.pur_gwtplatform_samples_views_MessageInsertView_dataStock = null;
_.pur_gwtplatform_samples_views_MessageInsertView_insertButton = null;
_.pur_gwtplatform_samples_views_MessageInsertView_keyStock = null;
_.pur_gwtplatform_samples_views_MessageInsertView_widget = null;
function pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_$createAndBindUi__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_2Lpur_gwtplatform_samples_views_MessageInsertView_2Lcom_google_gwt_user_client_ui_Widget_2(owner){
  var attachRecord0, cancelButton, dataStock, domId0, domId0Element, f_HTMLPanel1, f_HorizontalPanel10, f_HorizontalPanel4, f_HorizontalPanel6, f_HorizontalPanel8, f_Label5, f_Label7, f_Label9, f_LayoutPanel2, f_VerticalPanel3, insertButton, keyStock, pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0;
  domId0 = com_google_gwt_dom_client_Document_$createUniqueId__Lcom_google_gwt_dom_client_Document_2Ljava_lang_String_2($doc);
  f_Label5 = new com_google_gwt_user_client_ui_Label_Label__V;
  f_HorizontalPanel4 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  f_Label7 = new com_google_gwt_user_client_ui_Label_Label__V;
  keyStock = new com_google_gwt_user_client_ui_TextBox_TextBox__V;
  f_HorizontalPanel6 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  f_Label9 = new com_google_gwt_user_client_ui_Label_Label__V;
  dataStock = new com_google_gwt_user_client_ui_TextBox_TextBox__V;
  f_HorizontalPanel8 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  insertButton = new com_google_gwt_user_client_ui_Button_Button__V;
  cancelButton = new com_google_gwt_user_client_ui_Button_Button__V;
  f_HorizontalPanel10 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  f_VerticalPanel3 = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  f_LayoutPanel2 = new com_google_gwt_user_client_ui_LayoutPanel_LayoutPanel__V;
  f_HTMLPanel1 = new com_google_gwt_user_client_ui_HTMLPanel_HTMLPanel__Ljava_lang_String_2V((pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0 = new java_lang_StringBuilder_StringBuilder__V , com_google_gwt_core_client_impl_StringBufferImplArrayBase_$append__Lcom_google_gwt_core_client_impl_StringBufferImplArrayBase_2Ljava_lang_Object_2Ljava_lang_String_2V(pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0.java_lang_StringBuilder_data, $intern_133) , java_lang_StringBuilder_$append__Ljava_lang_StringBuilder_2Ljava_lang_String_2Ljava_lang_StringBuilder_2(pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0, com_google_gwt_safehtml_shared_SafeHtmlUtils_htmlEscape__Ljava_lang_String_2Ljava_lang_String_2(domId0)) , com_google_gwt_core_client_impl_StringBufferImplArrayBase_$append__Lcom_google_gwt_core_client_impl_StringBufferImplArrayBase_2Ljava_lang_Object_2Ljava_lang_String_2V(pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0.java_lang_StringBuilder_data, $intern_134) , new com_google_gwt_safehtml_shared_OnlyToBeUsedInGeneratedCodeStringBlessedAsSafeHtml_OnlyToBeUsedInGeneratedCodeStringBlessedAsSafeHtml__Ljava_lang_String_2V(com_google_gwt_core_client_impl_StringBufferImplArrayBase_$toString__Lcom_google_gwt_core_client_impl_StringBufferImplArrayBase_2Ljava_lang_Object_2Ljava_lang_String_2(pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0.java_lang_StringBuilder_data))).com_google_gwt_safehtml_shared_OnlyToBeUsedInGeneratedCodeStringBlessedAsSafeHtml_html);
  com_google_gwt_user_client_ui_VerticalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_VerticalPanel3, (com_google_gwt_user_client_ui_HasHorizontalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER));
  com_google_gwt_user_client_ui_HorizontalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_HorizontalPanel4, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER);
  f_Label5.com_google_gwt_user_client_ui_UIObject_element[$intern_73] = $intern_135;
  com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_Label5, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER);
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(f_Label5.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Saisir des donn\xE9es dans le LocalStorage');
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(f_Label5);
  f_Label5.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = '487px';
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel4, f_Label5);
  f_HorizontalPanel4.com_google_gwt_user_client_ui_UIObject_element[$intern_73] = 'gwt-StackPanel';
  f_HorizontalPanel4.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_179;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel4);
  com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_Label7, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1RIGHT);
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(f_Label7.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Cl\xE9 de stockage');
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(f_Label7);
  f_Label7.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_180;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel6, f_Label7);
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel6, keyStock);
  f_HorizontalPanel6.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_179;
  f_HorizontalPanel6.com_google_gwt_user_client_ui_CellPanel_table[$intern_111] = 3;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel6);
  com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_Label9, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1RIGHT);
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(f_Label9.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Donn\xE9e \xE0 stoquer');
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(f_Label9);
  f_Label9.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_180;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel8, f_Label9);
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel8, dataStock);
  f_HorizontalPanel8.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_179;
  f_HorizontalPanel8.com_google_gwt_user_client_ui_CellPanel_table[$intern_111] = 3;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel8);
  com_google_gwt_dom_client_DOMImplStandard_$setInnerText__Lcom_google_gwt_dom_client_DOMImplStandard_2Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2V(insertButton.com_google_gwt_user_client_ui_UIObject_element, $intern_139);
  insertButton.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_181;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel10, insertButton);
  com_google_gwt_dom_client_DOMImplStandard_$setInnerText__Lcom_google_gwt_dom_client_DOMImplStandard_2Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2V(cancelButton.com_google_gwt_user_client_ui_UIObject_element, 'Annuler');
  cancelButton.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_181;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel10, cancelButton);
  f_HorizontalPanel10.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = $intern_179;
  f_HorizontalPanel10.com_google_gwt_user_client_ui_CellPanel_table[$intern_111] = 10;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel10);
  f_VerticalPanel3.com_google_gwt_user_client_ui_CellPanel_table[$intern_137] = $intern_138;
  f_VerticalPanel3.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = '500px';
  com_google_gwt_user_client_ui_LayoutPanel_$insert__Lcom_google_gwt_user_client_ui_LayoutPanel_2Lcom_google_gwt_user_client_ui_Widget_2IV(f_LayoutPanel2, f_VerticalPanel3, f_LayoutPanel2.com_google_gwt_user_client_ui_ComplexPanel_children.com_google_gwt_user_client_ui_WidgetCollection_size);
  com_google_gwt_user_client_ui_LayoutPanel_$setWidgetLeftWidth__Lcom_google_gwt_user_client_ui_LayoutPanel_2Lcom_google_gwt_user_client_ui_Widget_2DLcom_google_gwt_dom_client_Style$Unit_2DLcom_google_gwt_dom_client_Style$Unit_2V(f_LayoutPanel2, f_VerticalPanel3, 153, (com_google_gwt_dom_client_Style$Unit_$clinit__V() , com_google_gwt_dom_client_Style$Unit_PX), 500, com_google_gwt_dom_client_Style$Unit_PX);
  com_google_gwt_user_client_ui_LayoutPanel_$setWidgetTopHeight__Lcom_google_gwt_user_client_ui_LayoutPanel_2Lcom_google_gwt_user_client_ui_Widget_2DLcom_google_gwt_dom_client_Style$Unit_2DLcom_google_gwt_dom_client_Style$Unit_2V(f_LayoutPanel2, f_VerticalPanel3, 29, com_google_gwt_dom_client_Style$Unit_PX, 196, com_google_gwt_dom_client_Style$Unit_PX);
  f_LayoutPanel2.com_google_gwt_user_client_ui_UIObject_element.style[$intern_72] = '194px';
  f_LayoutPanel2.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = '735px';
  f_HTMLPanel1.com_google_gwt_user_client_ui_UIObject_element.style[$intern_72] = '199px';
  f_HTMLPanel1.com_google_gwt_user_client_ui_UIObject_element.style[$intern_74] = '750px';
  attachRecord0 = com_google_gwt_uibinder_client_UiBinderUtil_attachToDom__Lcom_google_gwt_dom_client_Element_2Lcom_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_2(f_HTMLPanel1.com_google_gwt_user_client_ui_UIObject_element);
  domId0Element = com_google_gwt_dom_client_Document_$getElementById__Lcom_google_gwt_dom_client_Document_2Ljava_lang_String_2Lcom_google_gwt_dom_client_Element_2($doc, domId0);
  attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_origParent?com_google_gwt_dom_client_Node_$insertBefore__Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2(attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_origParent, attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_element, attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_origSibling):com_google_gwt_uibinder_client_UiBinderUtil_orphan__Lcom_google_gwt_dom_client_Node_2V(attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_element);
  com_google_gwt_user_client_ui_HTMLPanel_$addAndReplaceElement__Lcom_google_gwt_user_client_ui_HTMLPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_Element_2V(f_HTMLPanel1, f_LayoutPanel2, domId0Element);
  owner.pur_gwtplatform_samples_views_MessageInsertView_cancelButton = cancelButton;
  owner.pur_gwtplatform_samples_views_MessageInsertView_dataStock = dataStock;
  owner.pur_gwtplatform_samples_views_MessageInsertView_insertButton = insertButton;
  owner.pur_gwtplatform_samples_views_MessageInsertView_keyStock = keyStock;
  return f_HTMLPanel1;
}

function pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_MessageInsertView_1BinderImpl__V(){
}

function pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl(){
}

_ = pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_MessageInsertView_1BinderImpl__V.prototype = pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1views_1MessageInsertView_11BinderImpl_12_1classLit;
}
;
var com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1events_1InsertCompleteEvent_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2('pur.gwtplatform.samples.events.', 'InsertCompleteEvent'), com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1presenter_1MessageInsertPresenter_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_177, 'MessageInsertPresenter'), com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1views_1MessageInsertView_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_178, 'MessageInsertView'), com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1presenter_1MessageInsertPresenter$1_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_177, 'MessageInsertPresenter$1'), com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1presenter_1MessageInsertPresenter$2_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_177, 'MessageInsertPresenter$2'), com_google_gwt_lang_ClassLiteralHolder_Lpur_1gwtplatform_1samples_1views_1MessageInsertView_11BinderImpl_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_178, 'MessageInsertView_BinderImpl');
$entry(com_google_gwt_core_client_impl_AsyncFragmentLoader_onLoad__IV)(2);
